# vim: noexpandtab:ts=4:sw=4

provider = coldrye
os = debian
release = testing
feature = apt-cacher-ng
feature_version = 0.9.3
tag := $(shell date +"%Y%m%d%H%M%S")
image = $(os)-$(feature)

include ../../Makefile.in

